---
# use admin
# db.adminCommand({'setParameter': 1, 'failIndexKeyTooLong': false})
# db.iocs.createIndex({timestamp: -1})
# db.iocs.createIndex({createDate: -1})
# db.iocs.createIndex({modifyDate: -1})
# db.iocs.createIndex({"type": 1})
# db.iocs.createIndex({"provider": 1})
# db.iocs.createIndex({"value": 1, "url": 1}, {unique: true})
# db.iocs.createIndex({"value": "text"})
# db.iocs.createIndex({"uuid": 1}, {unique: true})
general:
  threads: 16
mongo:
  host: localhost
  port: 27018
  db: ioc
kaspersky:
  pemfile: /home/dave/git/misptools/feeds.pem
  tempdir: '/tmp'
feeds:
- name: CIRCL OSINT Feed
  disabled: true
  provider: CIRCL
  url: https://www.circl.lu/doc/misp/feed-osint
  format: misp
- name: The Botvrij.eu Data
  disabled: true
  provider: Botvrij.eu
  url: http://www.botvrij.eu/data/feed-osint
  format: misp
- name: inThreat OSINT Feed
  disabled: true
  provider: inThreat
  url: https://feeds.inthreat.com/osint/misp/
  format: misp
  timestampformat: '%sN'
- name: All current domains belonging to known malicious DGAs
  disabled: true
  provider: osint.bambenekconsulting.com
  url: http://osint.bambenekconsulting.com/feeds/dga-feed-high.csv
  format: csv
  category: Network activity
  type: domain
  delimiter: ','
  valuefield: 0 
  timestampfield: 2
  timestampformat: '%Y-%m-%d'
  commentfield: 1
- name: URLHaus Malware URLs
  disabled: true
  provider: Abuse.ch
  url: https://urlhaus.abuse.ch/downloads/csv/
  format: csv
  category: Network activity
  type: url
  delimiter: ','
  valuefield: 2
  timestampfield: 1
  timestampformat: '%Y-%m-%d %H:%M:%S'
  commentfield: 4
  tags: 
  - malware
- name: malwaredomainlist
  disabled: true
  provider: malwaredomainlist
  url: https://panwdbl.appspot.com/lists/mdl.txt
  format: csv
  category: Network activity
  type: ip-dst
  comment: malwaredomainlist
  delimiter: ','
- name: ZeuS compromised URL blocklist
  disabled: true
  provider: zeustracker.abuse.ch
  url: https://zeustracker.abuse.ch/blocklist.php?download=compromised
  format: csv
  type: url
  delimiter: ','
- name: Tor exit nodes
  disabled: true
  provider: TOR Node List from dan.me.uk
  url: https://www.dan.me.uk/torlist/?exit
  format: csv
  type: ip-src
  category: Network activity
  delimiter: ','
  tags:
  - tor
- name: alienvault reputation generic
  disabled: true
  provider: .alienvault.com
  url: http://reputation.alienvault.com/reputation.generic
  format: csv
  type: ip-dst
  category: Network activity
  delimiter: ' '
- name: Phishtank online valid phishing
  disabled: true
  provider: Phishtank
  url: http://data.phishtank.com/data/online-valid.csv
  format: csv
  ignorecsvheader: true
  type: url
  category: phishing
  valuefield: 1
  linkfield: 2
  timestampfield: 5
  timestampformat: '%Y-%m-%dT%H:%M:%S%z'
  commentfield: 7
  tags:
  - phishing
- name: Malwaredomains Malware Prevention
  disabled: true
  provider: Phishtank
  provider: malwaredomain.com
  url: http://mirror1.malwaredomains.com/files/justdomains
  format: csv
  type: domain
  category: malware
  tags:
  - malware
- name: cybercrime-tracker.net - all
  disabled: true
  provider: Phishtank
  provider: cybercrime-tracker.net
  url: http://cybercrime-tracker.net/all.php
  format: csv
  type: url
  category: cybercrime
  tags:
  - cybercrime
- name: Ransomware Tracker CSV Feed URLs
  disabled: true
  provider: Phishtank
  provider: Ransomware Tracker abuse.ch
  url: https://ransomwaretracker.abuse.ch/feeds/csv/
  format: csv
  type: url
  category: randsomeware
  valuefield: 4
  timestampfield: 0
  timestampformat: '%Y-%m-%d %H:%M:%S'
  commentfield: 2
  tags:
  - randsomeware
- name: Ransomware Tracker CSV Feed Domains
  disabled: true
  provider: Phishtank
  provider: Ransomware Tracker abuse.ch
  url: https://ransomwaretracker.abuse.ch/feeds/csv/
  format: csv
  type: domain
  category: randsomeware
  valuefield: 3
  timestampfield: 0
  timestampformat: '%Y-%m-%d %H:%M:%S'
  commentfield: 2
  tags:
  - randsomeware
- name: OpenPhish url list
  disabled: true
  provider: openphish.com
  url: https://openphish.com/feed.txt
  format: csv
  type: url
  category: phishing
  tags:
  - phishing
- name: Kaspersky Malicious URL Data Feed
  disabled: true
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/64/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Phishing URL Data Feed
  disabled: true
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/59/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Botnet CnC URL Data Feed
  disabled: true
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/65/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Malicious Hash Data Feed
  disabled: true
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/66/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Ransomware URL Data Feed
  disabled: true
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/99/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: listdynamic dns providers
  disabled: true
  provider: http://dns-bh.sagadc.org
  url: http://dns-bh.sagadc.org/dynamic_dns.txt
  format: csv
  delimiter: ' '
  commentfield: 2
- name: malc0de.com malicious domains
  disabled: true
  provider: malc0de.com
  url: http://malc0de.com/bl/BOOT
  format: csv
  delimiter: ' '
  type: domain
  valuefield: 1
  tags:
  - malware
- name: Kaspersky Malicious URL Exact Data Feed
  disabled: false
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/117/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Phishing URL Exact Data Feed
  disabled: false
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/116/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
- name: Kaspersky Botnet CnC URL Exact Data Feed
  disabled: false
  provider: Kaspersky
  url: https://wlinfo.kaspersky.com/api/v1.0/feeds/115/updates/
  format: kaspersky
  timestampformat: '%d.%m.%Y %H:%M'
